""" Initial 

Revision ID: 2bedc9f1a2ef
Revises: 
Create Date: 2025-08-05 04:18:58.075761

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bedc9f1a2ef'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_intent',
    sa.Column('urgency', sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='urgency'), nullable=False),
    sa.Column('is_instant', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_intent',
    sa.Column('ttl', sa.Interval(), nullable=True),
    sa.Column('errata_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('login_session',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('json_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('record_intent_id', sa.Integer(), nullable=True),
    sa.Column('project_intent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_intent_id'], ['project_intent.id'], ),
    sa.ForeignKeyConstraint(['record_intent_id'], ['record_intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_object', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposition')
    op.drop_table('stream')
    op.drop_table('login_session')
    op.drop_table('user')
    op.drop_table('record_intent')
    op.drop_table('project_intent')
    # ### end Alembic commands ###
